//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostosRecetas.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CostosRecetas.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar ingrediente.
        /// </summary>
        internal static string AddIngr {
            get {
                return ResourceManager.GetString("AddIngr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar receta.
        /// </summary>
        internal static string AddRecipe {
            get {
                return ResourceManager.GetString("AddRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string AlertAccept {
            get {
                return ResourceManager.GetString("AlertAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string AlertCancel {
            get {
                return ResourceManager.GetString("AlertCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polvo de hornear.
        /// </summary>
        internal static string BakingPowder {
            get {
                return ResourceManager.GetString("BakingPowder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicarbonato de sodio.
        /// </summary>
        internal static string BakingSoda {
            get {
                return ResourceManager.GetString("BakingSoda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantequilla.
        /// </summary>
        internal static string Butter {
            get {
                return ResourceManager.GetString("Butter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para obtener resultados más precisos, se recomienda que los ingredientes de la receta estén en la misma unidad de medida o en unidades que se puedan convertir directamente (por ejemplo, gramos a miligramos o litros a mililitros). Evite convertir entre diferentes tipos de medidas, como gramos a tazas, ya que representan propiedades diferentes como masa y volumen..
        /// </summary>
        internal static string CalcWarning {
            get {
                return ResourceManager.GetString("CalcWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cacao en polvo.
        /// </summary>
        internal static string Cocoa {
            get {
                return ResourceManager.GetString("Cocoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leche condensada.
        /// </summary>
        internal static string CondensedMilk {
            get {
                return ResourceManager.GetString("CondensedMilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taza.
        /// </summary>
        internal static string cup {
            get {
                return ResourceManager.GetString("cup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar ingrediente.
        /// </summary>
        internal static string EditIngr {
            get {
                return ResourceManager.GetString("EditIngr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar receta.
        /// </summary>
        internal static string EditRecipe {
            get {
                return ResourceManager.GetString("EditRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huevos.
        /// </summary>
        internal static string Eggs {
            get {
                return ResourceManager.GetString("Eggs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leche evaporada.
        /// </summary>
        internal static string EvaporatedMilk {
            get {
                return ResourceManager.GetString("EvaporatedMilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harina.
        /// </summary>
        internal static string Flour {
            get {
                return ResourceManager.GetString("Flour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        internal static string g {
            get {
                return ResourceManager.GetString("g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el ingrediente.
        /// </summary>
        internal static string IngrAdded {
            get {
                return ResourceManager.GetString("IngrAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Eliminar el ingrediente.
        /// </summary>
        internal static string IngrDelete {
            get {
                return ResourceManager.GetString("IngrDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrediente.
        /// </summary>
        internal static string Ingredient {
            get {
                return ResourceManager.GetString("Ingredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredientes.
        /// </summary>
        internal static string Ingredients {
            get {
                return ResourceManager.GetString("Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredientes de la receta.
        /// </summary>
        internal static string IngredientsRecipe {
            get {
                return ResourceManager.GetString("IngredientsRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string IngrName {
            get {
                return ResourceManager.GetString("IngrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        internal static string IngrPrice {
            get {
                return ResourceManager.GetString("IngrPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        internal static string IngrQty {
            get {
                return ResourceManager.GetString("IngrQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al guardar el ingrediente.
        /// </summary>
        internal static string IngrSaveError {
            get {
                return ResourceManager.GetString("IngrSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad de medida.
        /// </summary>
        internal static string IngrUnit {
            get {
                return ResourceManager.GetString("IngrUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se actualizó el ingrediente.
        /// </summary>
        internal static string IngrUpdtd {
            get {
                return ResourceManager.GetString("IngrUpdtd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string L {
            get {
                return ResourceManager.GetString("L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lb.
        /// </summary>
        internal static string lb {
            get {
                return ResourceManager.GetString("lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mg.
        /// </summary>
        internal static string mg {
            get {
                return ResourceManager.GetString("mg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leche.
        /// </summary>
        internal static string Milk {
            get {
                return ResourceManager.GetString("Milk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faltan datos.
        /// </summary>
        internal static string MissingData {
            get {
                return ResourceManager.GetString("MissingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml.
        /// </summary>
        internal static string ml {
            get {
                return ResourceManager.GetString("ml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceite.
        /// </summary>
        internal static string Oil {
            get {
                return ResourceManager.GetString("Oil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oz.
        /// </summary>
        internal static string oz {
            get {
                return ResourceManager.GetString("oz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparación.
        /// </summary>
        internal static string Preparation {
            get {
                return ResourceManager.GetString("Preparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrucciones de preparación.
        /// </summary>
        internal static string PreparationInstr {
            get {
                return ResourceManager.GetString("PreparationInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receta.
        /// </summary>
        internal static string Recipe {
            get {
                return ResourceManager.GetString("Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó la receta.
        /// </summary>
        internal static string RecipeAdded {
            get {
                return ResourceManager.GetString("RecipeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costos de la receta.
        /// </summary>
        internal static string RecipeCosts {
            get {
                return ResourceManager.GetString("RecipeCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Eliminar la receta.
        /// </summary>
        internal static string RecipeDelete {
            get {
                return ResourceManager.GetString("RecipeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles de la receta.
        /// </summary>
        internal static string RecipeDetails {
            get {
                return ResourceManager.GetString("RecipeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recetas.
        /// </summary>
        internal static string Recipes {
            get {
                return ResourceManager.GetString("Recipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al guardar la receta.
        /// </summary>
        internal static string RecipeSaveError {
            get {
                return ResourceManager.GetString("RecipeSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se actualizó la receta.
        /// </summary>
        internal static string RecipeUpdtd {
            get {
                return ResourceManager.GetString("RecipeUpdtd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la receta.
        /// </summary>
        internal static string RecpName {
            get {
                return ResourceManager.GetString("RecpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sal.
        /// </summary>
        internal static string Salt {
            get {
                return ResourceManager.GetString("Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar ingrediente.
        /// </summary>
        internal static string SearchPlaceholderIngr {
            get {
                return ResourceManager.GetString("SearchPlaceholderIngr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar receta.
        /// </summary>
        internal static string SearchPlaceholderRecipe {
            get {
                return ResourceManager.GetString("SearchPlaceholderRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azúcar.
        /// </summary>
        internal static string Sugar {
            get {
                return ResourceManager.GetString("Sugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cda.
        /// </summary>
        internal static string tbsp {
            get {
                return ResourceManager.GetString("tbsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo total.
        /// </summary>
        internal static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cdta.
        /// </summary>
        internal static string tsp {
            get {
                return ResourceManager.GetString("tsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ud.
        /// </summary>
        internal static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taza.
        /// </summary>
        internal static string Unit_cup {
            get {
                return ResourceManager.GetString("Unit_cup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gramo.
        /// </summary>
        internal static string Unit_g {
            get {
                return ResourceManager.GetString("Unit_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litro.
        /// </summary>
        internal static string Unit_L {
            get {
                return ResourceManager.GetString("Unit_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libra.
        /// </summary>
        internal static string Unit_lb {
            get {
                return ResourceManager.GetString("Unit_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miligramo.
        /// </summary>
        internal static string Unit_mg {
            get {
                return ResourceManager.GetString("Unit_mg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mililitro.
        /// </summary>
        internal static string Unit_ml {
            get {
                return ResourceManager.GetString("Unit_ml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onza.
        /// </summary>
        internal static string Unit_oz {
            get {
                return ResourceManager.GetString("Unit_oz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cucharada.
        /// </summary>
        internal static string Unit_tbsp {
            get {
                return ResourceManager.GetString("Unit_tbsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cucharadita.
        /// </summary>
        internal static string Unit_tsp {
            get {
                return ResourceManager.GetString("Unit_tsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad.
        /// </summary>
        internal static string Unit_unit {
            get {
                return ResourceManager.GetString("Unit_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vainilla.
        /// </summary>
        internal static string Vanilla {
            get {
                return ResourceManager.GetString("Vanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levadura.
        /// </summary>
        internal static string Yeast {
            get {
                return ResourceManager.GetString("Yeast", resourceCulture);
            }
        }
    }
}
